

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 
/**
 *
 * @author Victor
 */
import javax.swing.*;

public class G33Login extends javax.swing.JFrame {
    int LRN;
    /**
     * Creates new form Login
     */
    public G33Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField_PW = new javax.swing.JPasswordField();
        jLabel_AC = new javax.swing.JLabel();
        jLabel_PW = new javax.swing.JLabel();
        jButton_Login = new javax.swing.JButton();
        jLabel_genius = new javax.swing.JLabel();
        jLabel_EAC = new javax.swing.JLabel();
        jButton_AboutUs = new javax.swing.JButton();
        jTextField_AC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Genius - Login Page");

        jPasswordField_PW.setActionCommand("");
        jPasswordField_PW.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPasswordField_PW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_PWActionPerformed(evt);
            }
        });

        jLabel_AC.setText("User Name:");

        jLabel_PW.setText("Password:");

        jButton_Login.setText("Login");
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton_LoginActionPerformed(evt);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        jLabel_genius.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel_genius.setText("     -Genius-");
        jLabel_genius.setToolTipText("");

        jLabel_EAC.setFont(new java.awt.Font("Lucida Calligraphy", 2, 14)); // NOI18N
        jLabel_EAC.setText("  Educational Advancement Centre");
        jLabel_EAC.setToolTipText("");

        jButton_AboutUs.setText("About Us");
        jButton_AboutUs.setToolTipText("");
        jButton_AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AboutUsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap(165, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel_EAC, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                .addComponent(jLabel_genius, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                        layout.createSequentialGroup()
                                                .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton_AboutUs, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                        layout.createSequentialGroup().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel_PW, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel_AC, javax.swing.GroupLayout.DEFAULT_SIZE, 65,
                                                        Short.MAX_VALUE))
                                                .addGap(18, 18, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jPasswordField_PW,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 200,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jTextField_AC))))
                        .addContainerGap(165, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addContainerGap(54, Short.MAX_VALUE)
                        .addComponent(jLabel_genius, javax.swing.GroupLayout.PREFERRED_SIZE, 81,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_EAC, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_AC, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_AC, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jPasswordField_PW, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_PW, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_AboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_jButton_LoginActionPerformed
        // TODO add your handling code here:
        String user = jTextField_AC.getText();
        char[] Psd = jPasswordField_PW.getPassword();
        String psd = new String(Psd);

        if (user.equals("a") && psd.equals("a")) {
            JOptionPane.showMessageDialog(null, "Welcome, administration.");
           new G33Menu_admin().setVisible(true);
            super.dispose();

            //
            FileWriter FW=new FileWriter("G33ALoginRecord.csv", true);
            BufferedWriter BW=new BufferedWriter(FW);
    
            LRN = LRN ++;
            String LR_ID = "LR"+LRN;
            String U_ID = user;
    
            DateFormat dateFormat = new SimpleDateFormat("MM/dd/yy_hh:mm:ss");
            Date Rtime = new Date();
            String LR_T = dateFormat.format(Rtime);
                  
            String a[]= {LR_ID, U_ID, LR_T};
    
            BW.write(a[0]);BW.write(" ");
            BW.write(a[1]);BW.write(" ");
            BW.write(a[2]);BW.write(" ");
            BW.write("\n"); 

            BW.close();FW.close();
            

        } else if (user.equals("g1") && psd.equals("g")) {
            JOptionPane.showMessageDialog(null, "Welcome, You are sucessfully logined.");
            new G33Menu_user().setVisible(true);
            super.dispose();
            //
            FileWriter FW=new FileWriter("G33ALoginRecord.csv", true);
            BufferedWriter BW=new BufferedWriter(FW);
    
            LRN = LRN ++;
            String LR_ID = "LR"+LRN;
            String U_ID = user;
    
            DateFormat dateFormat = new SimpleDateFormat("MM/dd/yy_hh:mm:ss");
            Date Rtime = new Date();
            String LR_T = dateFormat.format(Rtime);
                  
            String a[]= {LR_ID, U_ID, LR_T};
    
            BW.write(a[0]);BW.write(" ");
            BW.write(a[1]);BW.write(" ");
            BW.write(a[2]);BW.write(" ");
            BW.write("\n"); 

            BW.close();FW.close();
        } else if (user.equals("g2") && psd.equals("g")) {
            JOptionPane.showMessageDialog(null, "Welcome, You are sucessfully logined.");
            new G33Menu_user().setVisible(true);
            super.dispose();
            //
            FileWriter FW=new FileWriter("G33ALoginRecord.csv", true);
            BufferedWriter BW=new BufferedWriter(FW);
    
            LRN = LRN ++;
            String LR_ID = "LR"+LRN;
            String U_ID = user;
    
            DateFormat dateFormat = new SimpleDateFormat("MM/dd/yy_hh:mm:ss");
            Date Rtime = new Date();
            String LR_T = dateFormat.format(Rtime);
                  
            String a[]= {LR_ID, U_ID, LR_T};
    
            BW.write(a[0]);BW.write(" ");
            BW.write(a[1]);BW.write(" ");
            BW.write(a[2]);BW.write(" ");
            BW.write("\n"); 

            BW.close();FW.close();
        }else if (user.equals("g3") && psd.equals("g")) {
            JOptionPane.showMessageDialog(null, "Welcome, You are sucessfully logined.");
            new G33Menu_user().setVisible(true);
            super.dispose();
            //
            FileWriter FW=new FileWriter("G33ALoginRecord.csv", true);
            BufferedWriter BW=new BufferedWriter(FW);
    
            LRN = LRN ++;
            String LR_ID = "LR"+LRN;
            String U_ID = user;
    
            DateFormat dateFormat = new SimpleDateFormat("MM/dd/yy_hh:mm:ss");
            Date Rtime = new Date();
            String LR_T = dateFormat.format(Rtime);
                  
            String a[]= {LR_ID, U_ID, LR_T};
    
            BW.write(a[0]);BW.write(" ");
            BW.write(a[1]);BW.write(" ");
            BW.write(a[2]);BW.write(" ");
            BW.write("\n"); 

            BW.close();FW.close();            
        }else {
            JOptionPane.showMessageDialog(null, "Invalid username or password");
        }
    }// GEN-LAST:event_jButton_LoginActionPerformed

    private void jPasswordField_PWActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPasswordField_PWActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jPasswordField_PWActionPerformed

    private void jButton_AboutUsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_AboutUsActionPerformed
        // TODO add your handling code here:
        new G33About_Us().setVisible(true);
        super.dispose();
    }// GEN-LAST:event_jButton_AboutUsActionPerformed

    /**
     * @param args the command line arguments
     * @throws IOException
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G33Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G33Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G33Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G33Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new G33Login().setVisible(true);
            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AboutUs;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JLabel jLabel_AC;
    private javax.swing.JLabel jLabel_EAC;
    private javax.swing.JLabel jLabel_PW;
    private javax.swing.JLabel jLabel_genius;
    private javax.swing.JPasswordField jPasswordField_PW;
    private javax.swing.JTextField jTextField_AC;
    // End of variables declaration//GEN-END:variables
}
